import type { Metadata } from "next";

import "./globals.css";

import { ThemeProvider } from "@/providers/theme.provider";

import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "ZOZO Pet's Service",
  description: "Generated by create next app",
  icons: {
    icon: "/images/icons/Logo.webp",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" suppressHydrationWarning>
      <body
        className={` font-normal antialiased bg-background-light dark:bg-background-dark  transition-color  duration-700 `}
      >
        <ThemeProvider>
          <Toaster richColors position="top-right" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
