import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
// import "./fonts/css/kalam.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import NavBar from "./components/navBar";
import { ThemeProvider } from "./theme.provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const globalFont = localFont({
src:'./fonts/Quicksand-Bold.woff2',
variable:'--font-global',


})
const displayFont = localFont({
  src:'./fonts/Kalam-Bold.woff2',
  variable:'--font-display'
  
  })

export const metadata: Metadata = {
  title: "ZOZO Pet's Service",
  description: "Generated by create next app",
  icons:{
    icon:'/images/icons/Logo.webp'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" suppressHydrationWarning>
      <body
        className={`${globalFont.variable} ${displayFont.variable} antialiased bg-background-light dark:bg-background-dark p-3 `}
      >
        <ThemeProvider>
          <GoogleOAuthProvider clientId={process.env.CLIENT_ID!}>
            <NavBar />

            {children}
          </GoogleOAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
