import type { Metadata } from "next";

import { GoogleLogin, GoogleOAuthProvider } from "@react-oauth/google";
import Login from "@/components/features/auth/login";

export const metadata: Metadata = {
  title: "ZOZO Pet's Service",
  description: "Generated by create next app",
  icons: {
    icon: "/images/icons/Logo.webp",
  },
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <GoogleOAuthProvider clientId={process.env.CLIENT_ID!}>
        {children}
      </GoogleOAuthProvider>
    </>
  );
}
